#!/usr/bin/env python3
"""Run and summarize the higher-capacity gradient-usability control.

The configuration is fixed before the boundary-dynamics runs.  It was selected
on the disjoint calibration seed 17 using only implicit differentiation.  The
reported run uses the five paper seeds and identical data, initialization,
architecture, optimizer, and training schedule for every requested method.

At every epoch the free equilibrium is obtained by the precise Newton solver.
For boundary_dynamic, both nudged endpoints and therefore every centered
EqProp parameter update are generated by boundary-damped physical dynamics.
This auxiliary control tests gradient usability without claiming end-to-end
physical free-phase relaxation.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd


PAPER_SEEDS = "101,202,303,404,505"
DATASETS = "moons,circles,xor"


def run_experiment(args: argparse.Namespace) -> None:
    command = [
        sys.executable,
        str(Path(__file__).with_name("benchmark_suite.py")),
        "--profile",
        "paper",
        "--datasets",
        DATASETS,
        "--chain-sizes",
        "17",
        "--seeds",
        PAPER_SEEDS,
        "--methods",
        args.methods,
        "--n-input-nodes",
        "12",
        "--n-rbf",
        "48",
        "--rbf-sigma",
        "0.55",
        "--epochs",
        "150",
        "--learning-rate-u",
        "0.01",
        "--learning-rate-structure",
        "0.001",
        "--damping-schedule",
        "graded_trace",
        "--damping-trace",
        "5.0",
        "--max-steps",
        "40000",
        "--tolerance",
        "2e-5",
        "--endpoint-step-multiplier",
        "10",
        "--phase-protocol",
        "exact_free_boundary_pair",
        "--workers",
        str(args.workers),
        "--output-dir",
        str(args.output_dir),
        "--resume",
    ]
    subprocess.run(command, check=True)


def summarize(output_dir: Path) -> None:
    runs_path = output_dir / "benchmark_runs.csv"
    if not runs_path.exists():
        raise FileNotFoundError(f"missing result file: {runs_path}")

    runs = pd.read_csv(runs_path)
    valid_flag = runs["valid_dynamic_run"].astype(str).str.lower().eq("true")
    valid = runs.loc[(runs["run_status"] == "completed") & valid_flag].copy()
    if valid.empty:
        raise RuntimeError("no completed valid runs are available")

    summary = (
        valid.groupby(["dataset", "method"], as_index=False)
        .agg(
            n_runs=("test_accuracy", "size"),
            test_accuracy_mean=("test_accuracy", "mean"),
            test_accuracy_std=("test_accuracy", "std"),
            test_accuracy_min=("test_accuracy", "min"),
            endpoint_convergence_fraction=("endpoint_convergence_fraction", "mean"),
            wall_time_seconds_mean=("wall_time_seconds", "mean"),
            gradient_relative_error_mean=("gradient_relative_error_mean", "mean"),
            gradient_relative_error_max=("gradient_relative_error_max", "max"),
            gradient_cosine_mean=("gradient_cosine_mean", "mean"),
            gradient_cosine_min=("gradient_cosine_min", "min"),
        )
        .sort_values(["dataset", "method"])
    )
    summary.to_csv(output_dir / "high_capacity_summary.csv", index=False)

    boundary = summary.loc[summary["method"] == "boundary_dynamic"]
    payload = {
        "configuration": {
            "datasets": DATASETS.split(","),
            "chain_size": 17,
            "n_input_nodes": 12,
            "n_rbf": 48,
            "rbf_sigma": 0.55,
            "epochs": 150,
            "seeds": [101, 202, 303, 404, 505],
            "damping_profile": "graded_trace",
            "damping_trace": 5.0,
            "endpoint_tolerance": 2e-5,
            "phase_protocol": "exact_free_boundary_pair",
            "free_phase": "Newton equilibrium at every epoch",
            "gradient_phases": "+beta and -beta use the requested dynamics",
        },
        "n_valid_runs": int(len(valid)),
        "all_requested_boundary_datasets_present": set(boundary["dataset"])
        == set(DATASETS.split(",")),
        "all_boundary_means_at_least_0_95": bool(
            len(boundary) == 3 and (boundary["test_accuracy_mean"] >= 0.95).all()
        ),
        "minimum_boundary_mean_accuracy": (
            float(boundary["test_accuracy_mean"].min()) if len(boundary) else None
        ),
    }
    (output_dir / "high_capacity_summary.json").write_text(
        json.dumps(payload, indent=2), encoding="utf-8"
    )

    methods = [
        method
        for method in ("boundary_dynamic", "standard_eqprop", "implicit_id")
        if method in set(summary["method"])
    ]
    datasets = DATASETS.split(",")
    fig, ax = plt.subplots(figsize=(7.2, 4.2))
    width = 0.24
    x = range(len(datasets))
    for index, method in enumerate(methods):
        selected = summary.loc[summary["method"] == method].set_index("dataset")
        means = [selected.loc[name, "test_accuracy_mean"] for name in datasets]
        errors = [selected.loc[name, "test_accuracy_std"] for name in datasets]
        positions = [value + (index - (len(methods) - 1) / 2) * width for value in x]
        ax.bar(positions, means, width, yerr=errors, capsize=3, label=method)
    ax.axhline(0.95, color="black", linestyle="--", linewidth=1, label="0.95 target")
    ax.set_xticks(list(x), datasets)
    ax.set_ylim(0.0, 1.02)
    ax.set_ylabel("Test accuracy")
    ax.set_title("Higher-capacity gradient-usability control")
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(output_dir / "high_capacity_accuracy.png", dpi=200)
    plt.close(fig)

    print(summary.to_string(index=False))
    print(json.dumps(payload, indent=2))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("results/high_capacity_gradient_control_v2"),
    )
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument(
        "--methods",
        default="implicit_id,standard_eqprop,boundary_dynamic",
        help="comma-separated methods passed to benchmark_suite.py",
    )
    parser.add_argument(
        "--summarize-only",
        action="store_true",
        help="skip execution and rebuild the summary from existing results",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.summarize_only:
        run_experiment(args)
    summarize(args.output_dir)


if __name__ == "__main__":
    main()
